# Generated by Django 4.1.5 on 2023-01-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
